name: Pages

on:
  push:
    branches:
      - main  # default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Build and Deploy
      uses: renzhaosy/hexo-deploy-action@master
      env:
        PERSONAL_TOKEN: ${{ secrets.HEXO_DEPLOY }}
        PUBLISH_REPOSITORY: jq-networks/the-cookbook # The repository the action should deploy to.
        BRANCH: main  # The branch the action should deploy to.
        PUBLISH_DIR: ./public # The folder the action should deploy.
